### ISSUE TITLE
 nVidia-NVML-QT5-6-tools is compatible with nvidia drivers 470 ?

### ISSUE THREAD

**Issue by Augusto7743** [Neo2003/nVidia-NVML-QT5-6-tools#1]
Hello Neo2003. All good with you ?
Firstly I want say thanks for creating that solution for all Nvidia users.
My question is your software is compatible with nvidia drivers 470 ?
I use an Kepler video card and driver 470 is the last version for that video card. However driver 470 has wayland support.
I only not use wayland mode because nvidia settings not work and so not has any access to gpu information usage and temperature and much less settings.

Thanks for reading.
Have an nice day =)

**Comment by Neo2003** [comment]
Hello
Unfortunately nvml is quite new for the non pro card. So you need a version 515 minimum and 555 is recommended.
See the change in nvml here: https://docs.nvidia.com/deploy/nvml-api/change-log.html#change-log
Version 470 will miss too many commands.

**Comment by Augusto7743** [comment]
Thanks for your reply =)
About "Version 470 will miss too many commands."
Have enough to change fan speed, underclock gpu and memory and read status information ?

**Comment by Neo2003** [comment]
SetFanSpeed is from driver 515
GetTemperature will work, but GetPowerUsage will not.
There is no API available to control the card in driver 470.

**Comment by Augusto7743** [comment]
Thanks for your reply.
In moment is better continue using X11 mode because has tools and commands to control the video card. Unhappily has wayland support, but not tools to control it.
An good week for you.

**Comment by Neo2003** [comment]
Exactly, if you can't have a newer driver, then Wayland is a no go. Even if nVidia update the settings tool for Wayland, they would use nvml, so it would require the latest driver.
